### PR TITLE
add brz token

### PR DESCRIPTION
**Pull request by henry-hz**
## Proposed changes
Add BRZ token to boost brazilian market BRZ liquidity

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by bejavu** [comment]
We are working on as we speak on a feature to create a issue a community currency around any existing token. I should be ready by next week, so you won't have to add BRZ token manually in the code.

**Comment by Marksmargon** [comment]
Hi Henry, 
We plan to upload a new version of the Studio next week that will let you do this very easily, after we have custom token support we can add this to the list of supported tokens.

**Comment by henry-hz** [comment]
great!

**Comment by leonprou** [comment]
@henry-hz we implemented custom token in this PR https://github.com/fuseio/fuse-studio/pull/203 :)
You can try to issue with custom token in the studio

**Pull request closed without merging**
